#!/usr/bin/python
#-*- coding: utf-8 -*-

import argparse
import os
import sys
from waltz import setup

def argparser():
    parser = argparse.ArgumentParser(description="Waltz is a web.py framework " \
                                         "for designing web apps in 3/4 time")
    parser.add_argument('init', nargs='?', metavar='init',
                        help="Start a waltz application")
    parser.add_argument('--name', dest='name', default="main.py",
                        help='Specify a name ')
    return parser

if __name__ == "__main__":
    parser = argparser()
    args = parser.parse_args()

    if not args.init:        
        sys.exit(parser.print_help())
    setup.init_scaffolding(os.getcwd(), appname=args.name)
